parameters:  
  Environment:
  ServiceConnection:

jobs:
- deployment: DeployFunctionApp
  pool:
    name: DAS - Continuous Deployment Agents
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: $(SubscriptionId)
            Location: $(ResourceGroupLocation)
            Environment: ${{ parameters.Environment }}
            TemplatePath: $(Pipeline.Workspace)/EmploymentCheck/azure/template.json
            ParametersPath: $(Pipeline.Workspace)/EmploymentCheck/azure/template.parameters.json
            IsMultiRepoCheckout: true
            TemplateSecrets:
              LoggingRedisConnectionString: $(LoggingRedisConnectionString)
              ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
              SharedStorageAccountConnectionString: $(SharedStorageAccountConnectionString)
        - template: azure-pipelines-templates/deploy/step/generate-config.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SourcePath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-employmentcheck
            TargetFileName: '*.schema.json'
            TableName: Configuration
        - template: azure-pipelines-templates/deploy/step/function-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            FunctionAppName: $(FunctionAppName)
            DeploymentPackagePath: $(Pipeline.Workspace)/EmploymentCheck/SFA.DAS.EmploymentCheck.Functions.zip
- template: azure-pipelines-templates/deploy/job/sql-dacpac-deploy.yml@das-platform-building-blocks
  parameters:
    AzureSubscription: ${{ parameters.ServiceConnection }}
    ServerName: $(SharedSQLServerFQDN)
    DatabaseName: $(DatabaseName)
    SqlUsername: $(SharedSQLServerUsername)
    SqlPassword: $(SharedSQLServerPassword)
    DacpacFile: $(Pipeline.Workspace)/DacpacArtifact/src/SFA.DAS.EmploymentCheck.Database/bin/Output/SFA.DAS.EmploymentCheck.Database.dacpac
    RunBlockOnPossibleDataLoss: ${{ parameters.RunBlockOnPossibleDataLoss }}
    Environment: ${{ parameters.Environment }}
    pool: DAS - Continuous Deployment Agents
    dependsOn: DeployFunctionApp